import { html } from 'uhtml-isomorphic'

const data = [
  {
    q: 'What is Gumcast?',
    a: html`<p>Gumcast is a Gumroad RSS feed generator service.  It lets you subscribe to Gumroad products as a podcast in Apple Podcasts and other podcast clients.</p>
      <p>Gumcast is a webapp that lets you generate <a href="https://en.wikipedia.org/wiki/Podcast">podcast</a> RSS feeds for any product in your <a href="https://gumroad.com">Gumroad</a> library. You can use these feeds to "subscribe" to a Gumroad product in your favorite podcast app which provides many benefits:</p>
      <ul>
        <li>Playback state tracking.</li>
        <li>New content notifications.</li>
        <li>Automatic downloads for offline use.</li>
        <li>Better UI/UX than the default Gumroad mobile apps.</li>
        <li>Consume your Gumroad podcasts in the same UI as every other podcast you listen to.</li>
        <li>Works with audio, video and even PDF documents!</li>
      </ul>`
  },
  {
    q: 'Why do I need to provide my Gumroad password?',
    a: html`<p>tldr; Due to a <a href="https://gumroad.com/api">Gumroad API</a> limitation, this is the only way to access Gumroad library content through the API.  Gumcast is working with Gumroad to improve this hopefully soon.</p>

      <p>Gumroad limits their content API to password auth only.  This is the same API used for their official <a href="https://gumroad.com/mobile">mobile app</a>.  If you would like to use a normal oAuth flow with Gumcast (so that your password is never shared with a 3rd party), <a href="https://help.gumroad.com/article/20-how-do-i-contact-gumroad">please encourage</a> Gumroad to support the "Authorization Code oAuth2" <a href="https://oauth.net/2/grant-types/">grant type</a> on their content API.</p>

    <p>Your password is never stored, logged or seen by the operations of this service.  All code is open source and freely auditable.</p>`
  },
  {
    q: 'What data does Gumcast store and where is it stored?',
    a: html`<p>All web app data is stored in <code>window.localstorage</code> under the <code>gumcast</code> key and is limited to a few things like application config, and session data.  This data lives locally in the browser you log in with.</p>

      <p>All RSS feed state is stored in the URL itself in form of search query parameter.  These URLs are stored locally in your podcast app.  The RSS feeds generated by Gumcast should be considered private and should never be shared.  They do not contain passwords, but they do contain session tokens which are tied to your Gumroad account.</p>

      <p>The Gumcast API is hosted on Heroku and never stores or logs your password or email address.  It does however process access tokens in order to retrieve your account library on your behalf.</p>`
  },
  {
    q: 'Is this service part of Gumroad?',
    a: 'No, this is an independent, third party, stateless application that uses Gumroad\'s content API to generate Podcast RSS feeds that can be subscribed to in a podcast app like Apple Podcasts.app.'
  },
  {
    q: 'Does this service mirror my Gumroad content?',
    a: html`No, all content is still stored and managed on Gumroad.  No copies of Gumroad is stored by this service.  Gumcast proxies various download links to provide a long lived URL for files, however a <a href="https://en.wikipedia.org/wiki/HTTP_302">302 redirect</a> is used to provide unproxied file downloads directly from Gumroad.`
  },
  {
    q: 'Someone is sharing a Gumcast feed with lots of people. Can you make them stop?',
    a: 'This is the same situation with Gumroad account sharing.  If you identify an account that is being shared with many people, work with Gumroad customer support to come to a resolution with the account owner in question.'
  },
  {
    q: 'Can people still access paid Gumroad content through Gumcast even after they end their subscription on Gumroad?',
    a: 'No, Gumcast can only provide access to what the Gumroad account has access to.  It does not provide copies of content or provide any additional access control beyond what Gumroad itself provides.'
  },
  {
    q: 'As a seller, do I need to set anything up with Gumcast so that customers can use this with my product?',
    a: html`No! All your customers need to do is log in with their own Gumroad account that has access to a purchase of your product at Gumcast and they can generate their personalized podcast feed for their individual subscription.`
  },
  {
    q: 'Can I stream large video/files with Gumcast?',
    a: html`Possibly, depending on how fast Gumroad is serving files that day.`
  },
  {
    q: 'The Gumcast website isn\'t working in my old browser/phone!',
    a: html`The Gumcast front-end was written for modern browsers to expedite development and maintenance.  Unfortunately, no effort will be made to support legacy browsers or vintage devices.  The RSS feeds should still work fine on the older devices though.`
  },
  {
    q: 'I found a bug/typo/something else is wrong.  How do I report?',
    a: html`Please visit the Github repository and open an issue: <a href="https://github.com/gumcast">github.com/gumcast</a>  Remember! Don't share any tokens/URLs in the issue as they are public.`
  },
  {
    q: 'This T-shirt I bought on Gumroad isn\'t a podcast.  What gives?',
    a: html`Gumroad doesn't have a great way to differentiate types of products.  If its in your library, then Gumcast will try to turn it into a podcast for you, even if the product is a T-Shirt.  To avoid issues, don't try to subscribe to products that don't contain media.`
  }
]

export function faq () {
  return html`
<section>
  <h2>FAQ</h2>
  <dl>
  ${data.map(qa => html.for(qa)`
    <dt>${qa.q}</dt>
    <dd>${qa.a}</dd>
    `)}
  </dl>
</section>
  `
}
